development:
  host: localhost
  database: whisper_development

test:
  host: localhost
  database: whisper_test

# set these environment variables on your prod server
production:
  uri: mongodb://heroku_app3519145:37o7a5e7l3bli6jpgl1bq4qtht@ds031627.mongolab.com:31627/heroku_app3519145
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
